import type { AppInitialProps, AppProps } from "next/app";
import Head from "next/head";
import Layout from "../components/Layout/Layout";
import { GlobalStyle } from "../styles/GlobalStyles";

interface ICustomApp {
  pageProps: any;
}

function MyApp({ Component, pageProps }: AppProps & ICustomApp) {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default MyApp;
