import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card/Card";
import { HomePageBody } from "../styles/HomePage.styles";
import PlacesMock from "../mocks/Places.json";
import Modal from "../components/Modal/Modal";
import { useState } from "react";

const Home: NextPage = () => {
  const [showModal, setShowModal] = useState(false);

  return (
    <>
      <Head>
        <title>Backpackd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showModal && <Modal modalText="Test" closeModal={() => {setShowModal(false)}} />}
      <HomePageBody>
        {PlacesMock.map(() => (
          <Card isProfile={false} clickHandler={() => setShowModal(true)} />
        ))}
      </HomePageBody>
    </>
  );
};

export default Home;
